### ISSUE TITLE
Is Ruby 2.4 supported?

### ISSUE THREAD

**Issue by olleolleolle** [mvz/rake-manifest#5]
The simplecov dep requires 2.5+

    simplecov (~> 0.19.0) was resolved to 0.19.0, which depends on
      Ruby (>= 2.5.0)

Perhaps the coverage could be done and used by higher-version Rubies?

**Comment by mvz** [comment]
I just loosened the simplecov dependency to allow building on 2.4. That's the easiest solution.

**Comment by olleolleolle** [comment]
I like this gem, by the way.
